name: Python CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint pytest-cov

    - name: Lint with pylint
      run: |
        pylint **/*.py

    - name: Check formatting with black
      run: |
        black --check .

    - name: unit tests 
      run: |
        PYTHONPATH="${PYTHON_PATH}:./src" python -m pytest -v tests/unit
        
    - name: functional tests
      run: |
        PYTHONPATH="${PYTHONPATH}:./src" python -m pytest -v tests/functional
    
    - name: Run coverage
      run: |
        PYTHONPATH="${PYTHONPATH}:./src" coverage run --source=./src -m pytest
 
    # - name: Run tests with coverage
    #   run: |
    #     pytest --cov=.
    #     pytest --cov-report=xml

    # - name: Upload coverage report
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
