name: Python CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint pytest-cov

    - name: Lint with pylint
      run: |
        pylint **/*.py

    - name: Check formatting with black
      run: |
        black --check .

    - name: Run tests with coverage
      run: |
        pytest --cov=.
        pytest --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.xml
